name: 'Apify Slack messenger'
description: 'Used to send slack messages from github workflows'
author: 'Apify'
inputs:
    slack-bot-user-oauth-access-token:
        required: false
        description: 'Slack bot token'
    slack-channel:
        required: false
        description: 'Slack channel to post message'
    message-type:
        required: false
        description: 'Type of message to send'
    message:
        required: false
        description: 'Text of message'
    color:
        required: false
        description: 'Color of message'
    version-tag:
        required: false
        description: 'Version tag'
runs:
    using: 'node12'
    main: 'dist/index.js'
